// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcofVfdGdr9mQwcTGjbQ9lie-T4BhB2k',
    appId: '1:1068515180002:web:b2220c68894901365acdbb',
    messagingSenderId: '1068515180002',
    projectId: 'chatapp-515c2',
    authDomain: 'chatapp-515c2.firebaseapp.com',
    storageBucket: 'chatapp-515c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrY9rY2JvWdKt9L6Z5hmIH_pv8T2Bfok',
    appId: '1:1068515180002:android:aa7096727c2d470f5acdbb',
    messagingSenderId: '1068515180002',
    projectId: 'chatapp-515c2',
    storageBucket: 'chatapp-515c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9uVcfnlDw6tXr4hdaHCd3TUM_P0L0Wc',
    appId: '1:1068515180002:ios:8c5e3781d66b762b5acdbb',
    messagingSenderId: '1068515180002',
    projectId: 'chatapp-515c2',
    storageBucket: 'chatapp-515c2.appspot.com',
    iosClientId: '1068515180002-fqrtm934j71iai4acd75g0oib70h3tlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ9uVcfnlDw6tXr4hdaHCd3TUM_P0L0Wc',
    appId: '1:1068515180002:ios:8c5e3781d66b762b5acdbb',
    messagingSenderId: '1068515180002',
    projectId: 'chatapp-515c2',
    storageBucket: 'chatapp-515c2.appspot.com',
    iosClientId: '1068515180002-fqrtm934j71iai4acd75g0oib70h3tlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
